name:                trialchain-mock
version:             0.1.0.0
github:              "pva701/trialchain-mock"
license:             BSD3
author:              "Ilya Peresadin"
maintainer:          "pva701@gmail.com"
copyright:           "2019 Ilya Peresadin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pva701/trialchain-mock#readme>

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
- TypeApplications

dependencies:
- base >= 4.9 && < 5
- universum

ghc-options:
- -Wall
- -fno-warn-orphans
- -Widentities
- -Wincomplete-record-updates
- -Werror


library:
  source-dirs: src
  build-tools:
  - autoexporter
  dependencies:
    - aeson
    - aeson-options
    - base16-bytestring
    - containers
    - cryptonite
    - fmt
    - memory
    - mtl
    - persist
    - unliftio
    - servant
    - servant-server
    - warp

executables:
  trialchain-mock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trialchain-mock

tests:
  trialchain-mock-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover
    dependencies:
    - trialchain-mock
    - aeson
    - hspec
    - QuickCheck
